### ISSUE TITLE
nodes(t=x) function of a DynGraph() object returns the list of degrees of all nodes rather than the list of nodes.

### ISSUE THREAD

**Issue by dayanandv** [GiulioRossetti/dynetx#109]
As per documentation, the `nodes(t=x)` function of the class `DynGraph`, should be returning a **list of the nodes** in the graph at the snapshot `x`, as of now it is returning the **list of degrees** of each node at the snapshot `x`. 

The example in the documentation is as below:
```
>>> import dynetx as dn
>>> G = dn.DynGraph()   # or DiGraph, MultiGraph, MultiDiGraph, etc
>>> G.add_path([0,1,2], 0)
>>> G.nodes(t=0)
[0, 1, 2]
```
whereas, on execution, it works as below:
```
>>> import dynetx as dn
>>> G = dn.DynGraph()
>>> G.add_path([0,1,2], 0)
>>> G.nodes(t=0)
[1, 2, 1]
```

**Comment by GiulioRossetti** [comment]
Hi,
which version of DyNetX are you using?
I tested your example but it works fine for me.

Giulio

**Comment by dayanandv** [comment]
I am on version 0.2.3. I upgraded to 0.2.4 after your reply and now it seems to work just fine. Thank you.
