### ISSUE TITLE
how draw network?

### ISSUE THREAD

**Issue by gabriellimagomes15** [GiulioRossetti/dynetx#22]
Hello, 

How I can draw the network ??

Thanks very much

**Comment by GiulioRossetti** [comment]
Hi, currently dynetx does not implement visualization facilities for dynamic networks. We plan to add them in a future release.

**Comment by PiyushIITKGP19** [comment]
Did you add any visualization tool for dynetx?

**Comment by GiulioRossetti** [comment]
Hi, not so far.
We are searching for someone interested in contributing to that specific feature.
