### ISSUE TITLE
ValueError: The specified interaction extension is broader than the ones already present for the given nodes.

### ISSUE THREAD

**Issue by TinaMuro** [GiulioRossetti/dynetx#61]
I am trying to load edge lists(snapshots) using Dynetx from the file  but i am getting this error, how to solve?
g = dn.read_snapshots('times2.txt', nodetype=int, timestamptype=int)
example of the edge lists
7 8001 10
7 8003 10
7 8004 10
7 8005 10
7 8006 10
7 8030 3
7 8034 10
7 8035 10
7 8036 10
7 8037 10
7 8038 10
7 8040 10
7 8041 10
7 8043 10
7 8044 1
7 8047 10
7 8065 10
7 8070 2

**Comment by GiulioRossetti** [comment]
Hi, 
I've tried to replicate your issue but it seems not to show up in my tests.

Could you please try to install dynetx from the master branch and let me know if this behavior persists?
