### ISSUE TITLE
License in setup.py different from LICENSE file

### ISSUE THREAD

**Issue by rafguns** [GiulioRossetti/dynetx#66]
According to the LICENSE file, this package is under the BSD 2-clause license, but setup.py mentions GPLv3. Can you clarify which license applies? Thanks!

**Comment by GiulioRossetti** [comment]
Thanks for the issue, you are right there is a mismatch: tomorrow I'll update the setup.py, the proper license is the BSD.

Moreover, completely out of topic, thanks for the linkpred package: it's a couple of years that I use it as teaching support in my Network Science course.

**Comment by rafguns** [comment]
Thanks! Happy to hear linkpred is useful to you.

DynetX seems great by the way! Somehow I wasn't aware of it until a few
days ago but will definitely explore further.

Op vr 5 jun. 2020 23:17 schreef Giulio Rossetti <notifications@github.com>:
