### ISSUE TITLE
Unable to add Multigraph in dynetx

### ISSUE THREAD

**Issue by PM1212** [GiulioRossetti/dynetx#95]
I am trying to add MultiGraph or MultiDiGraph in dynetx:

import dynetx as dn
G = dn.MultiGraph(edge_removal=True)

but getting the error:
AttributeError: module 'dynetx' has no attribute 'MultiGraph'

**Comment by GiulioRossetti** [comment]
Hi,
temporal extensions of MultiDiGraph (MultiDynDiGraph) and MultiGraph (MultiDynGraph) are not yet implemented by dynetx.

If you are interested in their static counterparts networkx implements them.

**Comment by PM1212** [comment]
Ok... Thanks. 
Is the implementation going on now?

**Comment by GiulioRossetti** [comment]
It is planned, however I don't have a specific deadline for it. Right now I'm working on other extensions.

**Comment by PM1212** [comment]
Thanks and best of luck for that
